### ISSUE TITLE
Build Failed because of missing LabVIEW path

### ISSUE THREAD

**Issue by ThatsTheEnd** [chwebdude/LabViewBuild#5]
Hey Andréïs,
first of all, thanks for your extension in azure, pretty cool thinking!
When I tried it today, I got the error that LabVIEWCLI couldn't find the last used LabVIEW version. This happens sometimes and you have to specify the path to the LV exe:
![image](https://user-images.githubusercontent.com/66672184/99307517-e63d2f00-2856-11eb-99e2-637e5e6beb38.png)
Could this be added as parameter to the extension?
Cheers and thanks, Niko

**Comment by chwebdude** [comment]
Hi
I finally had some time to do a little update. I added your requested feature :)
In our environment we also had some trouble for cold-start-builds, so I added a retry option. But I couldn't really test it since it seems to work now...
Anyway, hope this helps you.

Cheers
Fabrice
